version: "3.9"

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
  nginx:
      build: 
        context: ./web
        dockerfile: nginx.Dockerfile
      ports:
        - "80:80"
      depends_on:
        - web
  logs:
      image: amir20/dozzle:latest
      container_name: dozzle
      volumes: ["/var/run/docker.sock:/var/run/docker.sock"]
      ports: ["9876:8080"]

volumes:
  postgres_data:
