version: "3.9"

services:
  db:
    build: 
      context: ./database
      dockerfile: Dockerfile.pg
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - pg_data:/var/lib/postgresql/data/


  app:
    build: 
      context: .
      dockerfile: Dockerfile.app
    container_name: app
    entrypoint: ["/entrypoint.sh"]
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
  nginx:
      build: 
        context: ./web
        dockerfile: nginx.Dockerfile
      env_file:
        - .env
      ports:
        - "80:80"
      depends_on:
        - app
  logs:
      image: amir20/dozzle:latest
      container_name: dozzle
      volumes: ["/var/run/docker.sock:/var/run/docker.sock"]
      ports: ["9876:8080"]

volumes:
  pg_data:
