apiVersion: apps/v1
kind: Deployment
metadata:
  name: meu-site-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: meu-site
  template:
    metadata:
      labels:
        app: meu-site
    spec:
      containers:
      - name: meu-site-profissional
        image: andrepreira/meu-site-profissional:1.0.0
